<?php $isProductPage = stristr($block->getRequest()->getFullActionName(), 'catalog_product_view'); ?>
<?php $childHtml = $block->getChildHtml('', true); ?>
<?php $mainEntity = $block->getChildHtml('main.entity'); ?>
<?php if ($isProductPage && $childHtml): ?>
<script type="application/ld+json">
    <?= $block->escapeQuote($childHtml) ?>
</script>
<?php endif; ?>

<script type="application/ld+json">
[{
    "@context": "https://schema.org/",
    "@type": "<?= $block->escapeQuote($block->getPageType()) ?>",
    "publisher": {
        "@type": "Organization",
        "name": "<?= $block->escapeQuote($block->getStore()->getName()); ?>",
        "url": "<?= $block->escapeUrl($block->getStore()->getBaseUrl()); ?>",
        "logo": {
            "@type": "ImageObject",
            "url": "<?= $block->escapeUrl($block->escapeQuote($block->getStoreLogoUrl())); ?>"
        }
    }
    <?php if ($mainEntity != $childHtml): ?>
        <?= $block->escapeQuote($mainEntity); ?>
    <?php endif; ?>
    <?php $block->unsetChild('main.entity');?>

    <?php if (!$isProductPage && $childHtml): ?>
        <?= $block->escapeHtml($childHtml); ?>
    <?php endif; ?>
}]
</script>
