<script type="application/ld+json">
{
    "@context": "https://schema.org/",
	"@type": "ContactPage",
	"mainEntity": {
	    "@type": "<?php echo $block->getConfig('structureddata/contact/type') ?>",
	    "@id": "<?php echo $block->getStore()->getBaseUrl() ?>",
	    "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getStore()->getName()); ?>",
	    "image": "<?php echo $block->getStoreLogoUrl(); ?>",
	    "address": {
	        "@type": "PostalAddress",
                "streetAddress": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getStreetAddress()); ?>"
	        "addressLocality": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getConfig('general/store_information/city')); ?>",
	        "addressRegion": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getConfig('general/store_information/region_id')); ?>",
	        "postalCode": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getConfig('general/store_information/postcode')); ?>",
	        "addressCountry": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getConfig('general/store_information/country_id')); ?>"
	    },
	    "telephone": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getConfig('general/store_information/phone')); ?>",
	    "email": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getConfig('trans_email/ident_general/email')); ?>",
	    "url": "<?php echo $block->getStore()->getBaseUrl() ?>",
<?php if ($block->isLocalBusiness()): ?>
        "geo": {
            "@type": "GeoCoordinates",
            "latitude": "<?php echo $block->getConfig('structureddata/contact/latitude') ?>",
            "longitude": "<?php echo $block->getConfig('structureddata/contact/longitude') ?>"
        }
<?php endif; ?>
	}
}
</script>