,
"mainEntity": {
    "@type": "<?= $block->escapeQuote($block->getConfig('structureddata/contact/type')) ?>",
    "@id": "<?= $block->$escapeQuote($block->getStore()->getBaseUrl()); ?>",
    "name": "<?= $block->escapeQuote($block->getStore()->getName()); ?>",
    "image": "<?= $block->escapeUrl($block->getStoreLogoUrl()); ?>",
    <?php if (trim($block->escapeQuote($block->getStreetAddress()), ' ,\t\n\r\0\x0B') !== ''): ?>
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "<?= $block->escapeQuote($block->getStreetAddress()); ?>",
        "addressLocality": "<?= $block->escapeQuote($block->getConfig('general/store_information/city')); ?>",
        "addressRegion": "<?= $block->escapeQuote($block->getConfig('general/store_information/region_id')); ?>",
        "postalCode": "<?= $block->escapeQuote($block->getConfig('general/store_information/postcode')); ?>",
        "addressCountry": "<?= $block->escapeQuote($block->getConfig('general/store_information/country_id')); ?>"
    },
    <?php endif; ?>
    "telephone": "<?= $block->escapeQuote($block->getConfig('general/store_information/phone')); ?>",
    "email": "<?= $block->escapeQuote($block->getConfig('trans_email/ident_general/email')); ?>",
    "url": "<?= $block->escapeUrl($block->getStore()->getBaseUrl()); ?>"
<?php if ($block->isLocalBusiness() && trim($block->getConfig('structureddata/contact/latitude')) !== ''): ?>
    ,"geo": {
        "@type": "GeoCoordinates",
        "latitude": "<?= $block->escapeQuote($block->getConfig('structureddata/contact/latitude')) ?>",
        "longitude": "<?= $block->escapeQuote($block->getConfig('structureddata/contact/longitude')) ?>"
    }
<?php endif; ?>
}
