<script type="application/ld+json">
{
    "@context": "https://schema.org/",
    "@type": "WebPage",
    "publisher": {
        "@type": "Organization",
        "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getStore()->getName()); ?>",
        "url": "<?php echo $block->getStore()->getBaseUrl() ?>",
        "logo": {
            "@type": "ImageObject",
            "url": "<?php echo $block->getStoreLogoUrl(); ?>"
        }
    },
    "mainEntity": {
        "@type": "Product",
        <?php if ($block->getBrand()): ?>
            "brand": {
                "@type": "Brand",
                "name": "<?php /* @escapeNotVerified */ echo $block->stripTags($block->getBrand()); ?>"
            },
        <?php endif; ?>
        <?php if ($block->getReviewsCount()): ?>
            "aggregateRating": {
                "@type": "AggregateRating",
                "bestRating": "5",
                "worstRating": "1",
                "ratingValue": "<?php echo $block->getReviewsRating(); ?>",
                "reviewCount": "<?php echo $block->getReviewsCount(); ?>",
                "itemReviewed": {
                    "@type": "Thing",
                    "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($block->getProduct()->getName())); ?>"
                }
            },
            <?php foreach ($this->getReviews() as $review): ?>
                "review": {
                    "@type": "Review",
                    "author": {
                        "@type": "Person",
                        "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($review->getNickname()); ?>"
                    },
                    "datePublished": "<?php echo date('Y-m-d', strtotime($review->getCreatedAt())); ?>",
                    "reviewBody": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($review->getDetail())); ?>",
                    "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($review->getTitle())); ?>",
                    "publisher": {
                        "@type": "Organization",
                        "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->getStore()->getName()); ?>"
                    },
                    "reviewRating": {
                        "@type": "Rating",
                        "bestRating": "5",
                        "worstRating": "1",
                        "ratingValue": "<?php echo $review->getRatingValue(); ?>"
                    }
                },
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if ($block->getProduct()->getMpn()): ?>
            "mpn": "<?php /* @escapeNotVerified */ echo $block->stripTags($block->getProduct()->getMpn()); ?>",
        <?php endif; ?>
        <?php if ($block->getProduct()->getMaterial()): ?>
            "material": "<?php /* @escapeNotVerified */ echo $block->getAttributeText('material'); ?>",
        <?php endif; ?>
        <?php if ($block->getProduct()->getColor()): ?>
            "color": "<?php /* @escapeNotVerified */ echo $block->getAttributeText('color'); ?>",
        <?php endif; ?>
        "name": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($block->getProduct()->getName())); ?>",
        "sku": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($block->getProduct()->getSku())); ?>",
        "description": "<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($block->getDescription())); ?>",
        "image": "<?php /* @escapeNotVerified */ echo $block->stripTags($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()); ?>",
        "offers": {
            "@type": "Offer",
            "price": <?php echo $block->getProduct()->getPrice(); ?>,
            "priceCurrency": "<?php echo $block->getStore()->getCurrentCurrency()->getCode() ?>",
            "availability": "http://schema.org/<?php echo $block->getProduct()->isAvailable() ? 'InStock' : 'OutOfStock'; ?>",
            "itemCondition": "http://schema.org/NewCondition"
        },
        "weight": {
            "@type": "QuantitativeValue",
            "value": "<?php echo $block->getProduct()->getWeight(); ?>",
            "unitText": "<?php echo $block->getConfig('general/locale/weight_unit'); ?>"
        }
    }
}
</script>