<?php
    $product = $block->getProduct();
    if ($product) {
        $productSku = $product->getSku();
    }
?>
<script async>
    // Function to fetch offers JSON
    function fetchOffersSchema(SKU) {
        fetch(window.BASE_URL + 'rest/V1/structure_data/offers/' + SKU)
        .then(response => response.json())
        .then((data) => {
            if (!data.length && !data[0].offers) return;
            injectOffersSchema(data[0]);
        });
    }

    // Function to inject offers schema into structured data
    function injectOffersSchema(offersData) {
        const structuredData = document.getElementById('structured-data');
        const structuredDataJson = JSON.parse(structuredData.textContent);
        structuredDataJson.mainEntity.offers = offersData.offers;
        structuredData.textContent = JSON.stringify(structuredDataJson);
    }

    // Call fetchOffersSchema function with the product ID
    var productSKU = "<?= $productSku ?>";
    if (productSKU) fetchOffersSchema(productSKU);
</script>

