<?php if ($crumbs && is_array($crumbs)): ?>
<div class="breadcrumbs">
    <ul class="items">
        <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
            <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
            <?php if ($crumbInfo['link']): ?>
                <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                   title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                </a>
            <?php elseif ($crumbInfo['last']): ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>


<?php if ($crumbs && is_array($crumbs)): ?>
<script type="application/ld+json">
{
    <?php $position = 1; ?>
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
    <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
    {
            "@type": "ListItem",
            "position": "<?= (int)$position ?>",
            "item": {
                "@id": "<?= $block->escapeUrl($crumbInfo['link']) ?>",
                "name": "<?= $block->escapeHtml($crumbInfo['label']) ?>"
            }
    }
        <?= $crumbInfo['last'] ? '' : ',' ?>
    <?php endforeach; ?>
    ]
}
</script>
<?php endif; ?>
